In [1]:
import gym
import numpy as np

In [2]:
env = gym.make('FrozenLake-v0')

In [3]:
# Initialize table with all zeros
Q = np.zeros([env.observation_space.n,env.action_space.n])

# Set learning parameters
lr = .8
y = .95
num_episodes = 2000

# Create list to contain total rewards and steps per episode
jList = []
rList = []

for i in range(num_episodes):
    # Reset environment and get first new observation
    s = env.reset()
    rAll = 0
    d = False
    j = 0
    
    # The Q-Table learning algorithm
    while j < 99:
        j+=1
        
        # Choose an action by greedily (with noise) picking from Q table
        a = np.argmax(Q[s,:] + np.random.randn(1,env.action_space.n)*(1./(i+1)))
        
        # Get new state and reward from environment
        s1,r,d,_ = env.step(a)
        
        # Update Q-Table with new knowledge
        Q[s,a] = Q[s,a] + lr*(r + y*np.max(Q[s1,:]) - Q[s,a])
        
        rAll += r
        s = s1
        if d == True:
            break
            
    jList.append(j)
    rList.append(rAll)

In [4]:
print "Score over time: " +  str(sum(rList)/num_episodes)

Score over time: 0.6025


In [5]:
print "Final Q-Table Values"
print Q

Final Q-Table Values
[[  1.99106990e-01   8.38557145e-03   8.13389332e-03   9.25503398e-03]
 [  3.15672914e-04   2.05579508e-03   1.54873984e-05   1.04323394e-01]
 [  1.81333619e-03   1.03312830e-01   1.95826452e-03   3.46222288e-03]
 [  4.75833919e-04   9.34100400e-04   7.25265845e-04   5.64657681e-02]
 [  4.02474319e-01   8.49766067e-04   8.35807056e-04   8.34742737e-04]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  1.30293655e-04   1.61719847e-06   1.65679933e-01   8.49275060e-08]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  4.02713095e-03   2.78463960e-03   2.52718945e-03   4.81148652e-01]
 [  8.53908432e-04   5.54558070e-01   1.06899513e-03   0.00000000e+00]
 [  6.60899528e-01   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   1.25225309e-03   7.93010408e-01   1